# Generated by Django 4.2.6 on 2023-10-18 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('jumlah', models.IntegerField()),
                ('harga', models.IntegerField()),
                ('keterangan', models.TextField()),
                ('merk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sparepart.merk')),
            ],
        ),
    ]
