# Generated by Django 4.2.6 on 2023-12-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparepart', '0002_remove_sparepart_harga_sparepart_rak'),
    ]

    operations = [
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('id_krw', models.IntegerField()),
            ],
        ),
    ]
