# Generated by Django 4.2.7 on 2023-12-05 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sparepart', '0003_karyawan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Karyawan',
        ),
    ]
